/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список предстоящих встреч.
         *     В одном списке показаны бронирования всех типов событий,
         *     отсортированные по времени начала.
         */
        get: operations["Admin_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий, опубликованных владельцем. */
        get: operations["Admin_listEventTypes"];
        put?: never;
        /**
         * @description Создать тип события.
         *     Владелец публикует новый шаблон встречи и задаёт его id (slug).
         *
         *     Ошибки:
         *     - 400 Bad Request: невалидные данные (в т.ч. некорректный формат slug).
         *     - 409 Conflict: тип события с таким id (slug) уже существует.
         */
        post: operations["Admin_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список видов брони, доступных гостю.
         *     Возвращает название, описание и длительность.
         */
        get: operations["Public_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование на выбранный слот.
         *
         *     Ошибки:
         *     - 409 Conflict: слот уже занят (глобальная занятость по времени,
         *     даже если бронь была на другой тип события).
         *     - 400 Bad Request: слот вне окна записи (14 дней) либо не лежит
         *     на сетке слотов / невалидные данные.
         *     - 404 Not Found: тип события не найден.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты для выбранного типа события.
         *
         *     Слоты формируются на 14 дней, начиная с текущей даты, с шагом, равным
         *     durationMinutes типа события. Занятые любым бронированием слоты
         *     помечаются available: false (или исключаются — см. реализацию).
         */
        get: operations["Public_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование — запись гостя на конкретный слот. */
        Booking: {
            /** @description Уникальный идентификатор брони (UUID). */
            readonly id: string;
            /** @description Идентификатор типа события (slug), к которому относится бронь. */
            eventTypeId: components["schemas"]["EventTypeId"];
            /**
             * Format: date-time
             * @description Начало встречи (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи (UTC) = start + durationMinutes типа события.
             */
            end: string;
            /** @description Имя гостя. */
            guestName: string;
            /** @description Email гостя. */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Момент создания брони (UTC).
             */
            readonly createdAt: string;
        };
        /** @description Данные для создания бронирования. Гость указывает слот и контактные данные. */
        BookingCreate: {
            /**
             * Format: date-time
             * @description Начало выбранного свободного слота (UTC).
             */
            start: string;
            /** @description Имя гостя. */
            guestName: string;
            /** @description Email гостя. */
            guestEmail: string;
        };
        /** @description Единая модель ошибки для всех 4xx-ответов. */
        Error: {
            /** @description Машиночитаемый код ошибки, напр. "slot_taken", "out_of_window", "not_found". */
            code: string;
            /** @description Человекочитаемое сообщение. */
            message: string;
        };
        /**
         * @description Тип события — шаблон встречи, который публикует владелец.
         *     Длительность задаёт шаг сетки доступных слотов для этого типа.
         */
        EventType: {
            /** @description Человекочитаемый идентификатор (slug), заданный владельцем. Уникален. */
            id: components["schemas"]["EventTypeId"];
            /** @description Название типа события. */
            title: string;
            /** @description Описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах. Определяет шаг сетки слотов.
             */
            durationMinutes: number;
        };
        /**
         * @description Данные для создания типа события.
         *     id — человекочитаемый идентификатор (slug), задаёт владелец; используется
         *     в публичных URL и должен быть уникальным (дубль → 409 Conflict).
         */
        EventTypeCreate: {
            /** @description Человекочитаемый идентификатор (slug), задаёт владелец. */
            id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /**
         * @description Человекочитаемый идентификатор типа события (slug).
         *     Задаётся владельцем, должен быть уникальным, используется в публичных URL
         *     (напр. /public/event-types/30min/slots). Только строчные латинские буквы,
         *     цифры и дефис. Пример: "30min".
         */
        EventTypeId: string;
        /**
         * @description Владелец календаря — единственный заранее заданный профиль.
         *     Используется по умолчанию в админской части. Read-only.
         */
        Owner: {
            /** @description Отображаемое имя владельца. */
            name: string;
            /** @description Контактный email владельца (необязательно). */
            email?: string;
        };
        /**
         * @description Слот — производная сущность, не хранится в БД.
         *     Формируется из рабочего окна владельца и длительности типа события
         *     в пределах окна записи (14 дней от текущей даты).
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота (UTC) = start + durationMinutes.
             */
            end: string;
            /** @description Свободен ли слот (false, если уже занят любым бронированием). */
            available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Admin_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Admin_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Public_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор типа события (slug), напр. "30min". */
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Public_listSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор типа события (slug), напр. "30min". */
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
